# Generated by Django 5.2.5 on 2025-09-20 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('acc_num', models.BigAutoField(default=123456789, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_num', models.PositiveBigIntegerField(unique=True)),
                ('profile', models.ImageField(upload_to='profile_pics')),
                ('aadhar_photo', models.ImageField(upload_to='aadhar_details')),
                ('pin', models.CharField(max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=7)),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=32)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acc_type')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
            ],
        ),
    ]
