# Generated by Django 5.2.5 on 2025-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
