# Generated by Django 5.2.5 on 2025-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bankdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='acc_num',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
